version: "3.5"

services:
  app:
    image: ${REGISTRY_URL}/${CONTAINER_NAME}-app:${APP_VERSION}.${BUILD_NUMBER}
    container_name: ${CONTAINER_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile-dev
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    env_file: .env.dev
    restart: always
    ports:
      - target: ${SERVER_PORT}
        published: ${DOMAIN_PORT}
        protocol: tcp
        mode: host
  db:
    container_name: ${CONTAINER_NAME}-postgres
    image: postgres
    volumes:
      - './development/server/postgres:/var/lib/postgresql'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    env_file: .env.dev
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
