server:
  port: ${SERVER_PORT}
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    initialization-mode: never
  coredb:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    jdbc-url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    configuration:
      jdbc-url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    change-log: classpath:db/migration/changeLog.xml
    enabled: true
security:
  oauth2:
    resource:
      filter-order: 3
  auth-server-url: ${AUTH_SERVER}/oauth/check_token
  auth-server-url-me: ${AUTH_SERVER}/oauth/users/me
  auth-server: ${AUTH_SERVER}
  auth-server-client-id: ${AUTH_SERVER_CLIENT_ID}
  auth-server-client-secret: ${AUTH_SERVER_CLIENT_SECRET}
cdn:
  servers:
    1:
      host: ${FIRST_CDN_HOST}
      username: ${FIRST_CDN_HOST_USERNAME}
      password: ${FIRST_CDN_HOST_PASSWORD}
      uploadPath: ${FIRST_CDN_HOST_FOLDER}
      publicPath: ${FIRST_CDN_HOST_PUBLIC_PATH}
      alias: 1
  inRotation: [1]
languages:
  primaryLang: en